import { sqliteTable, text, integer, real } from "drizzle-orm/sqlite-core";
import { sql } from "drizzle-orm";

export const applications = sqliteTable("applications", {
  id: integer("id").primaryKey({ autoIncrement: true }),
  companyName: text("company_name").notNull(),
  jobTitle: text("job_title").notNull(),
  status: text("status").notNull().default("saved"),
  employmentType: text("employment_type").notNull().default("full_time"),
  workplaceType: text("workplace_type").notNull().default("remote"),
  compensationType: text("compensation_type").notNull().default("salary"),
  salaryAsked: real("salary_asked"),
  salaryMin: real("salary_min"),
  salaryMax: real("salary_max"),
  jobPostedAt: text("job_posted_at"),
  jobDescriptionUrl: text("job_description_url"),
  jobApplicationUrl: text("job_application_url"),
  jobApplicationStatusUrl: text("job_application_status_url"),
  jobDescription: text("job_description"),
  notes: text("notes"),
  companyIntel: text("company_intel"),
  workLocationCity: text("work_location_city"),
  workLocationState: text("work_location_state"),
  offersEquity: integer("offers_equity", { mode: "boolean" }).notNull().default(false),
  hiringManagerName: text("hiring_manager_name"),
  hiringManagerEmail: text("hiring_manager_email"),
  hiringManagerPhone: text("hiring_manager_phone"),
  hiringManagerLinkedinUrl: text("hiring_manager_linkedin_url"),
  applicationMedium: text("application_medium"),
  resumePath: text("resume_path"),
  resumeIsUrl: integer("resume_is_url", { mode: "boolean" }).default(false),
  attachedResumeVersionId: text("attached_resume_version_id"),
  coverLetterPath: text("cover_letter_path"),
  coverLetterIsUrl: integer("cover_letter_is_url", { mode: "boolean" }).default(false),
  coverLetterText: text("cover_letter_text"),
  dateApplied: text("date_applied"),
  createdAt: text("created_at").default(sql`(datetime('now'))`),
  updatedAt: text("updated_at").default(sql`(datetime('now'))`),
});
